apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBSskDuBVUsWDdb4gUHH2VOfnt/X8dkG5Pja3fbZDm2s1M73KXRrEDGe5tH+Hq2JMqRyT9nYN1jIbThX9WEHLe6k6y/WI4/JQji6iF+atrR6DZ4h1JaVGgeHH9OOhVNUxydrV/i4T4tcGcdjsE5qxl+Deo2JXAPwv0y4Sdumjx6eM1jwGLwvC/Em+TaF2bXruEbUsmEwNuTdEug7Dt1F4BLrlJX09+ryO5scVhZExgb/muTAzNuifdKON9WIHidDTammg+uJTateBN4/wSuZ/OzvKdNUceCB1ZbM/UXVc+2sQGrnc0doEum8cHAfShGgIb2sWOYvbE46DL2oMApVuyn4LgAw2lJJuc32EdR+TGRo0cDfemOVpIsQUy68yOegwogdx/K00OhrcIm/jLUTz10JUu/Ni+MjZXboq4K9BgMJYzTKaBbUzeDH/cB0XUx2aBptblZUjZvlavv9X8tIXenQNMGaU/0EL+EUbVuXu6/cFgnOgEWIT9Fwac9ySSPQ+WP4ANWWs1TiW3abtsod8XjsNajKAFJNjI/aVlIbLc5IdOlsYm+mYGXkwjrVa1MNfRSRUMICG35S6gGp2W4Nj9SRVM+G3dC3dk+4gbFgk0GIgJqqtcdsFnV3XW3ISS+VScOLUAC6G43zpsRGJQmYsC29fShQX65OdmGbTcbIr6enzDHnJWYD8/PAR6TN7MAKBP85eLN7Ky2Hfois/6lTKiFf7WFxKRR4tmeWYBcpN6ZsKhLnlpESGDA
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
status: {}

